Fix #5 Added support for Python3
conjurinc/summon-keyring pull request #6
Opened 2019-11-25 21:21 UTC by infamousjoeg

Added support for Python3.

Tested on Python 3.7 using Summon v0.8.0 successfully.

Updated [CHANGELOG.md](CHANGELOG.md) to include v0.3.0 for this change.

2019-11-25 21:23 UTC, sgnn7 commented
@infamousjoeg I should have some time tomorrow to take a look at this

2019-11-26 10:44 UTC, hughsaunders requested changes
This removes compatibility with 2.x for no real gain - it would work with 3.x in it's current state as long as python3 is the default python. 

If some 3x only features were being added/used then I'd support removing 2.x compatiblity. But removing 2.x compatibilty just because its being deprecated seems user hostile.

2019-11-26 14:15 UTC, infamousjoeg commented
Would an updated README that outlines _how_ to change from 2.7 to 3 be sufficient?

I agree with your review comment.

2019-11-26 16:46 UTC, sgnn7 commented
> If some 3x only features were being added/used then I'd support removing 2.x compatiblity. But removing 2.x compatibilty just because its being deprecated seems user hostile.

@hughsaunders https://pythonclock.org/. We should upgrade since Python2 is EOLd effectively starting with January: `Support officially stops January 1 2020,`.

@infamousjoeg In theory since this code is 1:1 in both python2 and 3, can we just change the line to be `python` instead of `python3` so that it will pick up whatever version the user has?

2019-11-26 16:54 UTC, sgnn7 commented
@infamousjoeg I'mma close this since it probably should work fine with machines that alias `python` to `python2` as well as machines that alias `python` to `python3`. In most cases, this will not be the latter case yet but it will change as distros remove py2 support.

@infamousjoeg Feel free to reopen if this doesn't work invoked with one of these python versions.

2019-11-26 16:54 UTC, closed without merging

2019-11-26 16:55 UTC, hughsaunders commented
@infamousjoeg a couple of things I think would be useful:

- Add some tests that run under python3. This ensures we don't break 3.x and signals to users that we are targeting python3.
- Add a comment in the readme that we are targetting python3 and how to use a virtualenv if the system python is v2.

2019-11-26 17:05 UTC, sgnn7 commented
I wonder if we can actually write this as a bash script that prefers py3 with py2 as fallback that then heredocs the code? Probably an overkill and pretty gnarly though.

2019-11-26 17:08 UTC, infamousjoeg commented
@hughsaunders that's a good idea... I see we have GitHub Actions enabled on this repository.  I'll create a Py3 GitHub workflow that tests functionality in my spare time.